sudo: false
language: python
cache: pip
before_script:
- pip install tox

# test script
script:  tox
notifications:
  on_success: change
  on_failure: always

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=flake8
    - python: 3.4
      env: TOXENV=pylint
    - python: 3.6
      env: TOXENV=py36

before_install:
  - pip install -U coveralls
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coveralls; fi